-- MySQL Script generated by MySQL Workbench
-- Sun Feb 14 12:05:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sandbox
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sandbox`;
-- -----------------------------------------------------
-- Schema sandbox
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `sandbox` DEFAULT CHARACTER SET utf8 ;
USE `sandbox` ;

-- -----------------------------------------------------
-- Table `sandbox`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(400) NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `userid_UNIQUE` (`userid` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sandbox`.`boxes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boxes` ;

CREATE TABLE IF NOT EXISTS `boxes` (
  `boxid` INT NOT NULL AUTO_INCREMENT,
  `html` TEXT NULL,
  `css` TEXT NULL,
  `js` TEXT NULL,
  `name` VARCHAR(45),
  `userid` INT NOT NULL,
  PRIMARY KEY (`boxid`),
  UNIQUE INDEX `boxid_UNIQUE` (`boxid` ASC) VISIBLE,
  INDEX `userid_idx` (`userid` ASC) VISIBLE,
  CONSTRAINT `useridpk_useridfk`
    FOREIGN KEY (`userid`)
    REFERENCES `users` (`userid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


USE `sandbox` ;

INSERT INTO users VALUES
(NULL, 'keagan', 'keaganluttrell@gmail.com`', 'pass', 'url'),
(NULL, 'keagan1', 'keaganluttrell7@gmail.com', 'pass', 'url');

INSERT INTO boxes VALUES
(NULL,
'<div id="hello">Hello World! 1<div>',
'body {
      background-color: tomato;
      text-align: center;
      font-family: tahoma;
      height: 2000px
    }
    #hello {
      background-color: white;
    }',
'document.write("From Sandbox!");',
'name',
 1),
 (NULL,
'<div id="hello">Hello World! 2<div>',
'body {
      background-color: tan;
      text-align: center;
      font-family: tahoma;
      height: 2000px
    }
    #hello {
      background-color: white;
    }',
'document.write("From Sandbox!");',
'name',
 1),
 (NULL,
'<div id="hello">Hello World! 3<div>',
'body {
      background-color: salmon;
      text-align: center;
      font-family: tahoma;
      height: 2000px
    }
    #hello {
      background-color: white;
    }',
'document.write("From Sandbox!");',
'name',
 1),
 (NULL,
'<div id="hello">Hello World! 4<div>',
'body {
      background-color: lightseagreen;
      text-align: center;
      font-family: tahoma;
      height: 2000px
    }
    #hello {
      background-color: white;
    }',
'document.write("From Sandbox!");',
'name',
 1),
 (NULL,
'<div id="hello">Hello World! 5<div>',
'body {
      background-color: cornflowerblue;
      text-align: center;
      font-family: tahoma;
      height: 2000px
    }
    #hello {
      background-color: white;
    }',
'document.write("From Sandbox!");',
'name',
 1);

select b.boxid, b.html, b.css, b.js, `name` from users u, boxes b where u.userid = 1;


